apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobapp
  labels:
    app: job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job
  template:
    metadata:
      labels:
        app: job
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "jobapp"
    spec:
      containers:
      - name: job
        image: devrlsharedacr.azurecr.io/sentiment-job:working
      imagePullSecrets:
      - name: regcred
